[[curiosSettings]]
  visible = 1
  identifier = "head"

[[curiosSettings]]
  visible = 1
  identifier = "necklace"

[[curiosSettings]]
  identifier = "ring"
  visible = 1
  size = 2
  
[[curiosSettings]]
  visible = 1
  identifier = "back"